### ISSUE TITLE
Is the attribute classifier trained with cross entropy or binary cross entropy?

### ISSUE THREAD

**Issue by huge123** [dawitmureja/AVE#3]
Thanks for sharing the dataset. 
I found that there may be multiple labels for an attribute of a shot, so how the attribute classification task is formulated?
If it is a normal multi-class classification problem where the cross entropy is used for training, how did you deal with the multiple labels problem?

**Comment by dawitmureja** [comment]
Hi @huge123, sorry for my late reply.
In cases where there are multiple labels, we used the most frequent label as a GT for the classification tasks. Please refer to the supplementary material of our paper for class-wise distribution statistics.
